-- Generated by generate_glyphs.py. Do not edit by hand.
local W = {
  ds16=171, dxia=192, deye=174, dsub=154, measy=64, mpro=64, fk1=26, fv1=80,
  fk2=26, fv2=136, fk3=26, fv3=49, bpick=88, bpath=44, bdraft=88, bscore=88,
  bend=88, kstart=38, kok=38, kback=38, kpathb=76, kscb=76, kside=76, kquit=76,
  kcont=57, kset=26, kban=38, kuse=38, kenter=76, kagain=76, krew=76, kfight=38,
  kretry=38, kfail=38, kadv=38, kdef=38, kred=95, own=22, win=13, tagcup=28,
  tagup=28, tagprom=42, svs=16, mkwin=14, mklose=14, mkfight=14, mkcup=14,
  rn1=37, rn2=37, rn3=37, rn4=26, rn5=39, rn6=26, bn1=78, bn2=78, bn3=78,
  bn4=56, bn5=84, bn6=56, pvs=34, plose=28, pq=14, good=13, weak=13, nhle=44,
  ngen=47, nt1=27, ndk=32, nblg=45, ntsw=49, ncfo=46, nmvk=49, ng2=29, nkc=31,
  thle=34, tgen=37, tt1=21, tdk=25, tblg=35, ttsw=38, tcfo=36, tmvk=38, tg2=23,
  tkc=24, sc0=21, sc1=21, sc2=21, sc3=21, sc4=21, sc5=21, sc6=21, sc7=21,
  sc8=21, sc9=21, scd=20, e0=12, e1=12, e2=12, e3=12, e4=12, e5=12, e6=12,
  e7=12, e8=12, e9=12, ecln=6, lhle=25, lgen=27, lt1=16, ldk=18, lblg=25,
  ltsw=28, lcfo=25, lmvk=28, lg2=17, lkc=17, s28=22, mdot=19, bdot=27, pg2=43,
  pg3=43, pg4=43, pg5=43, pg6=43, pg7=43, em=14, s78=58, s74=58, s16k=84, s9=42,
  n8=29, n5=29, n13=58, n9=29, k0=42, k1=42, k2=42, k3=42, k4=42, k5=42, k6=42,
  k7=42, k8=42, k9=42, kdash=39, whle=77, wgen=82, wt1=48, wdk=55, wblg=78,
  wtsw=86, wcfo=79, wmvk=85, wg2=51, wkc=53, t2841=59, cln=7, sdash=27, vrs=26,
  lan=26, lbn=26, cmt=270, ph1=39, ph2=52, ph3=52, t2800=59, endstat=112,
  sttw=16, stdg=16, smdash=5, nxk=52, nxlab=24, live=24, nxdr=26, nxrh=26,
  nxbr=26, nxeld=39, nxpush=26, gplus=7, tm1=59, tm2=59, tm3=59, tw1=37, tw2=37,
  tw3=37, dg1=37, dg2=37, ev1=81, ev2=68, ev3=81, ev4=84, ev5=55, ev6=81,
  ev7=84, ev8=81, me01=110, me02=139, me02b=84, me04=84, me04p=81, me05=81,
  me06=81, me07=84, me09=97, me10=81, me11=81, me13=107, me15r=97, me17=107,
  me20b=84, me21=97, me24=152, me25=94, me26a=68, me26b=84, me14=84, me15=84,
  me16=97, me18=81, me27c=84, v0=64, vss=25, vsna=88, vsw=44, winr=16, pkr=16,
  bnr=16, plays=32, strong=32, wklab=32, pct=15, dot=16, sp=4, rtop=13, rjg=13,
  rmid=13, radc=13, rsup=13, rall=13, fall=22, ftop=22, fjg=22, fmid=22,
  fadc=22, fsup=22, nhero=26, nused=26, wrlab=32, wrbig=44, wna=88, qpct=48,
  itop=16, ijg=16, imid=16, iadc=16, isup=16, kokban=76, kokuse=76, kcancel=38,
  kprev=38, knext=38, q0=29, q1=29, q2=29, q3=29, q4=29, q5=29, q6=29, q7=29,
  q8=29, q9=29, d0=9, d1=9, d2=9, d3=9, d4=9, d5=9, d6=9, d7=9, d8=9, d9=9,
  sl=5, lb1=134, lb2=134, lb3=134, lb4=134, lb5=134, lb6=134, lb7=134, lb8=134,
  lb9=134, lb10=134, lb11=134, lb12=134, lb13=134, lb14=134, lb15=134, lb16=134,
  le1=66, le2=66, le3=66, le4=66, le5=66, lb17=134, lb18=134, lb19=134,
  lb20=134, bhome=89, bgacha=44, bprep=44, bbook=66, kplay=76, kdraw=57,
  kclose=38, klock=76, hdock=32, hbook=32, hprep=32, hplay=32, pts=26, dup=32,
  newc=16, rssr=25, rsr=17, rrare=9, ghint=128, phint=144, nokpts=64,
  pntheshy=44, pnzeus=44, pnbin=44, pncanyon=44, pntian=44, pnjiejie=44,
  pnfaker=44, pnrookie=44, pnknight=44, pnuzi=44, pnruler=44, pngala=44,
  pnming=44, pnmeiko=44, pnkeria=44, nmnasus=66, fnnasus=108, nmcamille=66,
  fncamille=108, nmksante=66, fnksante=108, nmornn=44, fnornn=72, nmambessa=66,
  fnambessa=108, nmjayce=44, fnjayce=72, nmchogath=66, fnchogath=108,
  nmfiora=66, fnfiora=108, nmjax=66, fnjax=108, nmrenekton=66, fnrenekton=108,
  nmviego=66, fnviego=108, nmkindred=44, fnkindred=72, nmkhazix=66,
  fnkhazix=108, nmjarvaniv=88, fnjarvaniv=144, nmnidalee=66, fnnidalee=108,
  nmolaf=66, fnolaf=108, nmshyvana=66, fnshyvana=108, nmleesin=44, fnleesin=72,
  nmgraves=88, fngraves=144, nmhecarim=88, fnhecarim=144, nmsylas=66,
  fnsylas=108, nmqiyana=66, fnqiyana=108, nmyone=44, fnyone=72, nmtalon=44,
  fntalon=72, nmlocke=44, fnlocke=72, nmryze=44, fnryze=72, nmviktor=66,
  fnviktor=108, nmsyndra=66, fnsyndra=108, nmakali=66, fnakali=108, nmahri=44,
  fnahri=72, nmezreal=88, fnezreal=144, nmcaitlyn=66, fncaitlyn=108,
  nmkalista=88, fnkalista=144, nmkaisa=44, fnkaisa=72, nmlucian=66,
  fnlucian=108, nmtristana=88, fntristana=144, nmzeri=44, fnzeri=72, nmjhin=22,
  fnjhin=36, nmyunara=66, fnyunara=108, nmjinx=66, fnjinx=108, nmkarma=66,
  fnkarma=108, nmbard=44, fnbard=72, nmbraum=44, fnbraum=72, nmrakan=22,
  fnrakan=36, nmpyke=44, fnpyke=72, nmlulu=44, fnlulu=72, nmrell=44, fnrell=72,
  nmnautilus=88, fnnautilus=144, nmthresh=44, fnthresh=72, nmalistar=88,
  fnalistar=144
}
local M = { w = W }
function M.draw(g, key, x, y, opts)
  if opts then g:image(key, x, y, opts) else g:image(key, x, y) end
  return W[key] or 0
end
function M.center(g, key, cx, y, opts)
  local w = W[key] or 0
  M.draw(g, key, cx - math.floor(w / 2), y, opts)
  return w
end
function M.span(g, keys, x, y, opts)
  local cx = x
  for i = 1, #keys do
    cx = cx + M.draw(g, keys[i], cx, y, opts)
  end
  return cx - x
end
function M.num(g, n, x, y, opts)
  local s = tostring(n)
  local cx = x
  for i = 1, #s do
    local ch = s:sub(i, i)
    if ch >= '0' and ch <= '9' then
      cx = cx + M.draw(g, 'd' .. ch, cx, y, opts)
    end
  end
  return cx - x
end
return M
